Repository notforrest/PocketPantry, pull requests merged in 2024-08, with the labels that each got.

#16 Update to Expo SDK 51
  app.json
  app/(tabs)/_layout.tsx
  app/(tabs)/manual/index.tsx
  app/(tabs)/my-pantry/index.tsx
  app/(tabs)/scan-receipt/confirmation.tsx
  app/(tabs)/scan-receipt/index.tsx
  package-lock.json
  package.json
Labels: major

#23 Update and enforce linter
  .eslintrc.js
  app/(tabs)/my-pantry/index.tsx
  app/(tabs)/scan-receipt/confirmation.tsx
  image.d.ts
  package-lock.json
  package.json
Labels: development

#25 Create What's New modal for landing page
  app/(tabs)/index.tsx
  components/whats-new-modal.tsx
Labels: enhancement

#29 Changed PocketChef to PocketPantry
  app.json
  package-lock.json
  package.json
Labels: documentation

#30 Added Supabase foundation
  package-lock.json
  package.json
  utils/supabase.ts
Labels: development

#33 Adds CI workflow
  .github/workflows/node.js.yml
  app/(tabs)/scan-receipt/parser.tsx
Labels: development

#35 Implement and connect Supabase user authentication
  app/(tabs)/_layout.tsx
  app/(tabs)/account/_layout.tsx
  app/(tabs)/account/index.tsx
  app/(tabs)/account/profile.tsx
  components/auth.tsx
  utils/supabase.ts
Labels: enhancement

#42 Redesign profile view
  app/(tabs)/account/edit-profile.tsx
  app/(tabs)/account/profile.tsx
Labels: enhancement

#45 Add error feedback for username or full name
  app/(tabs)/account/choose-full-name.tsx
  app/(tabs)/account/choose-username.tsx
  utils/ErrorMessages.tsx
  utils/ThemeProvider.tsx
Labels: bug, documentation
